
- description: Make investments for all investors
  for: $inputs.investors
  each:
    - contract: Token
      at: $deployed.token
      run: setInvestorWhitelist
      inputs:
        - addr: $item.account
          value: true
        - from: $inputs.managementAccount

    - contract: Token
      at: $deployed.token
      run: sendTransaction
      inputs:
        - from: $item.account
          value: $item.amount

- description: Mark sukuk as closed to new investment
  contract: Token
  at: $deployed.token
  run: finalizeFunding
  inputs:
    - $inputs.fiatPerEthAmount
    - from: $inputs.managementAccount
