
- description: Make investments for all investors
  for: $inputs.investors
  each:
    - contract: Token
      at: $deployed.token
      run: setInvestorWhitelist
      inputs:
        - addr: $item.account
          value: true
        - from: $inputs.managementAccount

    - contract: Token
      at: $deployed.token
      run: sendTransaction
      inputs:
        - from: $item.account
          value: $item.amount

- description: Mark sukuk as closed to new investment
  contract: Token
  at: $deployed.token
  run: finalizeFunding
  inputs:
    - $inputs.fiatPerEthAmount
    - from: $inputs.managementAccount

- description: Get balance of tokens held by custodian
  contract: CouponStorage
  at: $deployed.couponStorage
  run: balanceOf
  inputs:
    - _owner: $inputs.custodian
    - from: $inputs.custodian
      gasPrice: $inputs.gasPrice
  outputs:
    output: $inputs.custodianBalance

